### ISSUE TITLE
Slow job processing

### ISSUE THREAD

**Issue by Nas-77** [C9Glax/tranga#107]
Hi, I noticed from the web app that tranga processes  2 jobs at most in parallel (1 downloading and another one that checks for new chapters). So I was wondering if there is any way to speed up the job processing or make more jobs run in parallel? I think this will become a bottleneck when it is monitoring a few hundred mangas. Thanks

**Comment by C9Glax** [comment]
Hello.
This is intended behaviour. API-Request-Limits as well as firewalls will block without second thought which is why tranga tries to respect others as much as possible.
If someone starts requesting 10 pages a second the useragent will be blocked as well so being patient is part of the game. I have 130 Manga monitored, and the delay between requests per connector is around 1 second. That means I can check all Manga for updates in 2 Minutes, download new chapters (most often 2-5 á 30 pages) in another 2-3 Minutes.
While it is a bottleneck it is one that is intended to keep tranga alive as long as possible.

**Comment by C9Glax** [comment]
On the initial download if you have 100 Manga and 50 Chapters / 20 Pages that comes out to 100*50*20 = 100000 seconds, 1666 minutes, 27 hours.
If you download all of them from the same site. 
Tranga will parallel jobs for different sites, so that reduces that time.

**Comment by Nas-77** [comment]
I see so its better to use different sources, at least for the initial download. Thanks

**Comment by IsXGeo** [comment]
While I fully understand why you've made this decision, what if I happen to have a manga with over 3000 chapters containing anywhere from 10 - 25 images each. And I have more than one manga with a few hundred chapters. If it's a user-agent issue, could you allow the user to edit the user-agent in the same way FMD2 does?

**Comment by C9Glax** [comment]
@IsXGeo yup shouldn't be too difficult.

**Comment by C9Glax** [comment]
@IsXGeo So custom user-agent is now implemented, and you can override the rate-limits too.
`<tranga:port>/Settings/customRequestLimit?requestType=1&requestsPerMinute=1&connector=Mangaworld`
It's just not on the website yet.

**Comment by IsXGeo** [comment]
> @IsXGeo So custom user-agent is now implemented, and you can override the rate-limits too.
> 
> `<tranga:port>/Settings/customRequestLimit?requestType=1&requestsPerMinute=1&connector=Mangaworld`
> 
> It's just not on the website yet.

Neat, thanks. Just to confirm currently the way to modify the rate limit is to change the number through that browser url?
