### ISSUE TITLE
Manually add mangal scrappers

### ISSUE THREAD

**Issue by yacob841** [C9Glax/tranga#123]
Yes, I know how it sounds. The whole inspiration for this project was because of the issues that mangal caused. However, I think, if you are able to build in the functionality to add manually mangal scrappers it will help keep users loyal and buy time until you’ve developed more tranga scrappers. 

For example, if there was a manga I was looking for and it was only on a site that does not have a tranga scrapper but does have a mangal scrapper I’m going to need to keep my Kaizoku server running and using it to fill that gap (and some might feel like it’s not worth running both and will just continue using Kaizoku). Where if you can manually add mangal scrappers then there would hypothetically be no more need for Kaizoku anymore.

if this does get implemented, I would definitely say that there needs to be some sort of differentiation between the two. Maybe “(mangal)” after the site name or something along those lines.

**Comment by C9Glax** [comment]
I am not really trying to compete with anything, and user retention is not a goal.
I don't need to "buy time". In the first place this is a project I created for myself to use primarily and that I just open-sourced because if others want to use it, why not.
While it would be nice to have as many sites/scrapers as possible, that also means a lot of maintenance. With just the current 6 I am already busy enough, that I haven't touched the 7th that has been on the list.

**Comment by yacob841** [comment]
Totally makes sense. I was going to mention, I enjoy scripting (mostly Python) but I haven't touch c# yet and have almost no time with work and kids but I was thinking about trying to work on your scrappers to help add more sites. Not sure if you would be open to help but figured I can try making one and once I have it to what I believe could be working state I can send it to you to review and add if you want.

**Comment by C9Glax** [comment]
Just fork the project, develop your connector (preferably on a separate branch) and when you think you're done, create a PR!
