### ISSUE TITLE
POST /Test does not return anything

### ISSUE THREAD

**Issue by C9Glax** [C9Glax/tranga#125]
### What is broken?

https://github.com/C9Glax/tranga-website/pull/41#issuecomment-1937885794

**Comment by C9Glax** [comment]
@db-2001 
Can not reproduce either 😢 
![image](https://github.com/C9Glax/tranga/assets/13404778/22037085-38f8-4e78-bd2b-587cd24c07f8)
I get a 202 on all requests...
Just to make sure: You were using a POST-Method?

**Comment by db-2001** [comment]
Yeah I was just logging the response from the existing JavaScript code if I remember correctly and it worked for some and didn't for others. Maybe it's a JavaScript thing. Not too concerned since as of right now we don't use the response for anything. We might in the future if we want to confirm something has occured.
