### ISSUE TITLE
Download multiple at a time

### ISSUE THREAD

**Issue by yacob841** [C9Glax/tranga#130]
So far from what I have noticed, it appears that there is a queue system that only allows one download at a time and there is one queue for each website you are downloading from. So if you download from multiple websites you can have concurrent downloads occurring but if you are only downloading from one website it downloads one at a time.

I think it would be nice if either each manga can have its own queue (preferred) or having it still be one queue per site but download 3-5 chapters at a times. As of now it seems to take a long time, I had tried to download a manga with 140+ chapters and over 4 hours went by and it will still going (2200 Gb/s fiber connection so that's not the issue)

**Comment by C9Glax** [comment]
Rate Limits.
We do not want to appear a nuisance to these sites.
Ofc we could just download 20000 images all at once, but what would you do if 10 people did that to your service? Ban 'em.
Doesn't matter if it's different manga, because the requests are all made to the same site.

So yes, the initial download takes a while, but 
a) you won't be reading that fast anyways
b) any new chapters will be downloaded in about a minute or two.
