### ISSUE TITLE
Unable to display images such as covers

### ISSUE THREAD

**Issue by HamzaM** [C9Glax/tranga#40]
Nice work on Tranga, it fills up a huge void we've had in the manga self hosted world. 

I encountered this issue today 
<img width="1800" alt="CleanShot 2023-07-31 at 20 42 52@2x" src="https://github.com/C9Glax/tranga/assets/14812057/32df1fc3-9049-4619-8228-331b1cc1abd6">

As you can see, it tries to access images but something blocks it

Any idea how i can fix this ?

Also, it would be nice to make chapter selection possible through checkboxes as well so we can have a visual of what's been selected or manually select them one by one.

**Comment by C9Glax** [comment]
Hey there, thanks for the praises :)

Did you use the [provided dockerfile](https://github.com/C9Glax/tranga/blob/master/docker-compose.yaml)?
Otherwise mount the `imageCache` folder to `/usr/share/nginx/html/imageCache` in the website-container.

Also the cover.jpg is actually missing, so that won't go away, but it's only intended as a placeholder anyways.
However, even if the images are missing, there should be empty frames with the titles. Have you added any Mangas so far?

The chapterselection thing is for now very limited, and atm I am not very active in development of new features (espechially in regards to the website), because of some sins I commited in the past with this project... So it will have to wait until I atoned for those. :P

**Comment by HamzaM** [comment]
Yes I used that exact docker compose but with my own paths of course

**Comment by HamzaM** [comment]
After a few minutes i get this :/ 
<img width="1794" alt="CleanShot 2023-07-31 at 21 11 28@2x" src="https://github.com/C9Glax/tranga/assets/14812057/b285dc27-c33a-46de-983d-aeca8406b1e4">

**Comment by C9Glax** [comment]
Hmm okay, so it is actually having problems connecting to the api part.
Three things:

1. Do you have logs of the container?
2. The containers are both running on 192.168.1.2?
3. Can you navigate to 192.168.1.2:6531 and see if the container is running.

Perhaps I messed up somewhere when I rewrote a lot of stuff these last few days...

**Comment by C9Glax** [comment]
Okay so I just found one issue during creation of the settings file, where the `version` value would be null, crashing the program.
That might be related to this issue here
_Originally posted by @HamzaM in https://github.com/C9Glax/tranga/issues/40#issuecomment-1658984983_
(I guess you restarted the container?)
So if you can pull the latest again, that should let it connect to the api (hopefully)

**Comment by C9Glax** [comment]
Yeah that is the issue I mentioned with the version value. But seeing this also confirms that there is a `settings.json` otherwise there should be no null-warning.
```
    volumes:
      - ./tranga:/usr/share/Tranga-API #1 when replacing ./tranga replace #2 with same value
```
This is the part that mounts inside the container to `/usr/share`, if you haven't modified it, then inside the folder with the docker-compose, there should be a folder `tranga` inside of which is the settings.json

**Comment by HamzaM** [comment]
Changed the volumes to old ones and the settings.json file was there, i deleted it but am getting this now 
<img width="1800" alt="CleanShot 2023-07-31 at 23 56 38@2x" src="https://github.com/C9Glax/tranga/assets/14812057/7b192466-0601-4ad5-b41a-4bcefd8e967b">

**Comment by HamzaM** [comment]
No such file or directory, yet i get many files in /usr/share though 
<img width="692" alt="CleanShot 2023-08-01 at 19 11 42@2x" src="https://github.com/C9Glax/tranga/assets/14812057/c09c34ca-e71c-4b7e-bdc7-fd324390d32b">

**Comment by C9Glax** [comment]
uh i am stupid of course it's 
`docker exec tranga-website ls -la /usr/share/nginx/html`
not
`docker exec tranga-api ls -la /usr/share/nginx/html`

**Comment by HamzaM** [comment]
<img width="785" alt="CleanShot 2023-08-01 at 20 04 00@2x" src="https://github.com/C9Glax/tranga/assets/14812057/a9a6630b-c6ba-429d-818c-ca576bd14bdd">

Maybe a persmission error ?

**Comment by C9Glax** [comment]
And I guess imageCache ist empty?
`docker exec tranga-website ls -la /usr/share/nginx/html/imageCache
`

**Comment by HamzaM** [comment]
Indeed, it is empty. 
<img width="876" alt="CleanShot 2023-08-02 at 12 40 26@2x" src="https://github.com/C9Glax/tranga/assets/14812057/e1de8660-1577-4486-816b-91b9f580bc47">

**Comment by C9Glax** [comment]
Okay so here is what is probably going on:
If you run `docker exec tranga-api ls -la /usr/share/Tranga-API/imageCache` the files will (hopefully) be there.
If that is the case, then you have mounted the wrong directory to the website-container.
Can you show the `volumes` part of the docker-compose (make sure to censor personal stuff i guess).

**Comment by HamzaM** [comment]
This is what I got 
<img width="1170" alt="CleanShot 2023-08-02 at 18 05 23@2x" src="https://github.com/C9Glax/tranga/assets/14812057/b872beb4-ee7b-4d21-8317-420e84c7268b">

I basically got the example docker-compose but modified the mounted path on my end

**Comment by C9Glax** [comment]
Just curious:
Doesn't it matter wether `$CONFIG_PATH` is capitalized? Because it isn't in tranga-website.

**Comment by HamzaM** [comment]
Oh shoot, yes it should matter. I'll fix it right away and let you know. Idk how i didn't see this 😭

**Comment by HamzaM** [comment]
That was the issue, thanks @C9Glax !!!

**Comment by C9Glax** [comment]
Sometimes we look with our eyes, not our brain.
The amount of times I have stared at a line of code, knowing it was wrong, but not seeing the issue being a completely different command...
Glad it worked :)
