### ISSUE TITLE
Separate download and root manga folders

### ISSUE THREAD

**Issue by mgrimace** [C9Glax/tranga#43]
Hello,

I'm not sure if I'm missing this is the setup, is there a way to specific a separate downloads folder and root folder? Ideally, I'd like to have files temporarily downloaded to /downloads/manga, then have tranga move the completed files to /media/manga which Komga then monitors.

My apologies in advance if I'm misunderstanding the process here, and thanks for the info.

**Comment by C9Glax** [comment]
Hey!

Manga in transit are temporarily stored in a temp-folder (`/tmp` on linux, but since it's inside the container...) and afterwards moved to whereever `/Manga` in the [docker-compose](https://github.com/C9Glax/tranga/blob/master/docker-compose.yaml) is pointing.

Edit line 8 to say `- /media/manga:/Manga` and that should give you your wanted result.
